# Generated by Django 5.1.6 on 2025-02-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('machine_type', models.CharField(max_length=128)),
                ('cpus', models.IntegerField()),
                ('memory', models.IntegerField()),
            ],
        ),
    ]
