# Generated by Django 5.1.6 on 2025-02-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='job_submitted',
            new_name='task_submitted',
        ),
        migrations.RemoveField(
            model_name='event',
            name='job_status',
        ),
        migrations.AddField(
            model_name='event',
            name='task_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='task_status',
            field=models.IntegerField(choices=[(0, 'Not Submitted'), (1, 'Pending'), (2, 'Running'), (3, 'Completed'), (4, 'Failed'), (5, 'Cancelled')], default=0),
        ),
    ]
