# Generated by Django 5.1.6 on 2025-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_job_submitted_event_task_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cpus_per_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='memory_per_user',
        ),
        migrations.AddField(
            model_name='event',
            name='machine',
            field=models.TextField(choices=[('e2-medium', 'e2-medium'), ('n2-standard-2', 'n2-standard-2')], default='e2-medium'),
            preserve_default=False,
        ),
    ]
