# Generated by Django 5.1.6 on 2025-02-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_event_cpus_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='task_status',
        ),
    ]
